name: Ahoy.js
ui: tape
html: test/template.html
scripts:
  - dist/ahoy.js
  - test/test_helper.js
browsers:
  - name: chrome
    version: latest
  - name: safari
    version: latest
  # - name: ie
  #   version: latest
